inputSequence {
  header
  MD5
  SHA512
}
availableGenes {
  name
},
# Subtype
bestMatchingSubtype {
  displayWithoutDistance,
  distancePcnt,
  distance,
},
# Drug resistance
drugResistance (includeGenes: [CA, PR, RT, IN]) {
  gene { name, drugClasses {name, hasDrugResistMutations, hasSurveilDrugResistMutations, hasRxSelectedMutations} },
  drugScores {
    SIR, score, level, text,
    drug {
      name, fullName
      drugClass {
        name,
        fullName
      }
    }
  }
}
# Mutations
validationResults(includeGenes: [CA, PR, RT, IN]) {
  level
  message
},
alignedGeneSequences {
  gene {name},
  matchPcnt,
  prettyPairwise {
    positionLine,
    refAALine,
    alignedNAsLine,
    mutationLine
  }
}
mutations{
  text
  gene { name },
  reference,
  position,
  AAs,
  triplet,
  primaryType,
  isDeletion,
  isInsertion,
  isIndel,
  isDRM,
  isApobecMutation,
  isApobecDRM,
  isUnusual,
  hasStop,
  comments {name,type,text}
},
frameShifts {
  gene { name },
  position,
  size,
  text
},
mutationPrevalences {
  boundMutation {
    text
  },
  matched { subtypes { AA, percentageTreated, subtype { name } } }
}