FROM ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y apt-utils
RUN apt-get install -y wget
RUN apt-get install -y unzip
RUN apt-get install -y nano
RUN apt-get install -y python3-pip python-is-python3

# Install Git
RUN apt-get install -y git

# Install mamba
WORKDIR /micromamba
RUN apt-get install -y curl
RUN curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/1.4.1 | tar -xvj bin/micromamba
# RUN ["./bin/micromamba", "shell", "init", "-s", "bash", "-p", "/micromamba"]
ENV MAMBA_ROOT_PREFIX="/micromamba/bin/"
ENV PATH="${PATH}:/usr/local/bin/:${MAMBA_ROOT_PREFIX}"
RUN ["micromamba", "--version"]

# Install Strainline
WORKDIR /opt
RUN ["git", "clone", "https://github.com/HaploKit/Strainline.git"]
RUN ["micromamba", "create", "-n", "venv"]
RUN ["micromamba", "install", "-n", "venv", "-c", "bioconda", "-c", "conda-forge", "-y", "minimap2", "spoa", "samtools", "dazz_db", "daligner", "metabat2"]

# Install daccord
WORKDIR /opt
RUN ["wget", "https://github.com/gt1/daccord/releases/download/0.0.10-release-20170526170720/daccord-0.0.10-release-20170526170720-x86_64-etch-linux-gnu.tar.gz"]
RUN ["tar", "-zvxf", "daccord-0.0.10-release-20170526170720-x86_64-etch-linux-gnu.tar.gz"]
RUN ["rm", "daccord-0.0.10-release-20170526170720-x86_64-etch-linux-gnu.tar.gz"]
RUN ["ln", "-fs", "/opt/daccord-0.0.10-release-20170526170720-x86_64-etch-linux-gnu/bin/daccord", "/micromamba/bin/envs/venv/bin/daccord"]

# Install Snippy
RUN ["micromamba", "install", "-n", "venv", "-c", "bioconda", "-c", "conda-forge", "-y", "snippy==4.6.0"]
RUN ["micromamba", "install", "-n", "venv", "-c", "bioconda", "-y", "snpeff==4.5covid19"]

# Install BLAST+
RUN ["micromamba", "install", "-n", "venv", "-c", "bioconda", "-y","blast"]

RUN ["micromamba", "clean", "--all", "-y"]

RUN ["pip","install", "biopython", "pandas", "numpy"]
RUN ["pip", "install", "yattag", "sierrapy", "jinja2"]


COPY ./scripts /hiv64148/scripts
COPY ./settings /hiv64148/settings

RUN ["ln", "-fs", "/opt/Strainline/src/*", "/micromamba/bin/envs/venv/bin"]

WORKDIR /workspace
CMD ["/bin/bash"]
